// generated by scratchpad/atlas/atlas.mjs from the Higgsfield shard sheet (16 shards, 4x4)
// R,G = tangent-space normal xy, B = frost/structure, A = silhouette * (0.35 + 0.65 * thickness)
import { assetUrl } from "../assets";
export const SHARD_ATLAS_URL = assetUrl("shards-atlas.png"); // FROST: was '/shards-atlas.png'
export const SHARD_GRID = 4;
/** used extent of each cell (fraction of the cell), row-major from the top-left */
export const SHARD_CELLS: [number, number][] = [
  [0.8035, 0.94],
  [0.94, 0.8055],
  [0.7254, 0.94],
  [0.94, 0.8764],
  [0.94, 0.9233],
  [0.7478, 0.94],
  [0.94, 0.8079],
  [0.6781, 0.94],
  [0.94, 0.8965],
  [0.94, 0.8612],
  [0.7025, 0.94],
  [0.8094, 0.94],
  [0.94, 0.903],
  [0.8238, 0.94],
  [0.94, 0.7249],
  [0.8374, 0.94],
];
