import { createHash } from "node:crypto";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildSync } from "esbuild";
import {
  HYPERFRAME_RUNTIME_ARTIFACTS,
  HYPERFRAME_RUNTIME_CONTRACT,
  loadHyperframeRuntimeSource,
} from "../src/inline-scripts/hyperframe";
import { writeGeneratedFile } from "./writeGeneratedFile.js";

const thisDir = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(thisDir, "../dist");
const iifePath = resolve(distDir, HYPERFRAME_RUNTIME_ARTIFACTS.iife);
const esmPath = resolve(distDir, HYPERFRAME_RUNTIME_ARTIFACTS.esm);
const manifestPath = resolve(distDir, HYPERFRAME_RUNTIME_ARTIFACTS.manifest);

const runtimeSourceRaw = loadHyperframeRuntimeSource();
if (runtimeSourceRaw === null) {
  throw new Error("Cannot build runtime artifact: entry.ts not found at expected path");
}
const runtimeSource = `${runtimeSourceRaw}\n`;
const runtimeSha256 = createHash("sha256").update(runtimeSource, "utf8").digest("hex");
const buildId = process.env.HYPERFRAME_RUNTIME_BUILD_ID?.trim() || "dev";
const runtimeEntryPath = resolve(thisDir, "../src/runtime/entry.ts");
const esmBuild = buildSync({
  entryPoints: [runtimeEntryPath],
  bundle: true,
  write: false,
  platform: "browser",
  format: "esm",
  target: ["es2020"],
  minify: true,
  legalComments: "none",
});
const esmSource = `${esmBuild.outputFiles[0]?.text ?? ""}\n`;

const manifest = {
  version: process.env.HYPERFRAME_RUNTIME_VERSION?.trim() || "0.1.0",
  buildId,
  sha256: runtimeSha256,
  artifacts: {
    iife: HYPERFRAME_RUNTIME_ARTIFACTS.iife,
    esm: HYPERFRAME_RUNTIME_ARTIFACTS.esm,
  },
  contract: HYPERFRAME_RUNTIME_CONTRACT,
};

writeGeneratedFile(iifePath, runtimeSource);
writeGeneratedFile(esmPath, esmSource);
writeGeneratedFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

// ── Generate src/generated/runtime-inline.ts ──────────────────────────────
// This file is compiled by tsc into dist/ and provides the production-safe
// getHyperframeRuntimeScript() that returns the IIFE as a string constant —
// no esbuild, no file I/O, no import.meta.url arithmetic.
const inlineModulePath = resolve(thisDir, "../src/generated/runtime-inline.ts");
const escapedSource = JSON.stringify(runtimeSourceRaw);
writeGeneratedFile(
  inlineModulePath,
  [
    "// AUTO-GENERATED by scripts/build-hyperframes-runtime-artifact.ts — do not edit",
    `const RUNTIME_IIFE: string = ${escapedSource};`,
    "",
    "/**",
    " * Returns the pre-built hyperframe runtime IIFE as a string constant.",
    " * This is the production-safe path: no esbuild, no file I/O,",
    " * no import.meta.url arithmetic.",
    " */",
    "export function getHyperframeRuntimeScript(): string {",
    "  return RUNTIME_IIFE;",
    "}",
    "",
  ].join("\n"),
);

console.log(
  JSON.stringify({
    event: "hyperframe_runtime_artifacts_generated",
    buildId,
    distDir,
    iifePath,
    esmPath,
    manifestPath,
    inlineModulePath,
    sourceBytes: Buffer.byteLength(runtimeSource, "utf8"),
    esmBytes: Buffer.byteLength(esmSource, "utf8"),
    sha256: runtimeSha256,
  }),
);
